# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('practo_account', models.PositiveIntegerField(verbose_name='User')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='marketplace.Apps')),
            ],
            options={
                'db_table': 'user_apps',
                'verbose_name': 'UserApp',
                'verbose_name_plural': 'UserApps',
            },
        ),
    ]
