# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20170120_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='logo',
            field=models.ImageField(default='asdasda', upload_to=marketplace.models.upload_logo),
            preserve_default=False,
        ),
    ]
